// Autogenerated by scripts/foundry-bridge.js
// DO NOT EDIT MANUALLY — regenerate after each deployment.
//
// Generated at: 2026-04-29T15:07:52.828Z

import type { GenericContractsDeclaration } from "@/utils/scaffold/contract";

const deployedContracts = {
  "84532": {
      AgentRegistry: {
        address: "0x6ce3d4bf7c7140924c6ab7579b8b86dc9ebf7a02",
        abi:           [
              {
                  "type": "function",
                  "name": "acceptOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "approve",
                  "inputs": [
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "balanceOf",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "deactivateAgent",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "getAgent",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "agent",
                          "type": "tuple",
                          "internalType": "struct AgentRegistry.AgentMetadata",
                          "components": [
                              {
                                  "name": "ensName",
                                  "type": "string",
                                  "internalType": "string"
                              },
                              {
                                  "name": "capabilitiesHash",
                                  "type": "bytes32",
                                  "internalType": "bytes32"
                              },
                              {
                                  "name": "registeredAt",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "isActive",
                                  "type": "bool",
                                  "internalType": "bool"
                              }
                          ]
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getAgentByAddress",
                  "inputs": [
                      {
                          "name": "agentAddress",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getAgentByENS",
                  "inputs": [
                      {
                          "name": "ensName",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getApproved",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "isAgentActive",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "active",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "isApprovedForAll",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "name",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "owner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "ownerOf",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "pendingOwner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "reactivateAgent",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "registerAgent",
                  "inputs": [
                      {
                          "name": "ensName",
                          "type": "string",
                          "internalType": "string"
                      },
                      {
                          "name": "capabilitiesHash",
                          "type": "bytes32",
                          "internalType": "bytes32"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "renounceOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "safeTransferFrom",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "safeTransferFrom",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "data",
                          "type": "bytes",
                          "internalType": "bytes"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "setApprovalForAll",
                  "inputs": [
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "approved",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "supportsInterface",
                  "inputs": [
                      {
                          "name": "interfaceId",
                          "type": "bytes4",
                          "internalType": "bytes4"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "symbol",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "tokenURI",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "totalRegistered",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "total",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "transferFrom",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "transferOwnership",
                  "inputs": [
                      {
                          "name": "newOwner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "updateCapabilities",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "capabilitiesHash",
                          "type": "bytes32",
                          "internalType": "bytes32"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "event",
                  "name": "AgentDeactivated",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgentReactivated",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgentRegistered",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "agent",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "ensName",
                          "type": "string",
                          "indexed": false,
                          "internalType": "string"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "Approval",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "approved",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "ApprovalForAll",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "operator",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "approved",
                          "type": "bool",
                          "indexed": false,
                          "internalType": "bool"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "CapabilitiesUpdated",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "capabilitiesHash",
                          "type": "bytes32",
                          "indexed": false,
                          "internalType": "bytes32"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferStarted",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferred",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "Transfer",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "error",
                  "name": "AgentRegistry__AgentInactive",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "AgentRegistry__AlreadyRegistered",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "AgentRegistry__ENSAlreadyTaken",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "AgentRegistry__NotRegistered",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "AgentRegistry__NotTokenOwner",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ERC721IncorrectOwner",
                  "inputs": [
                      {
                          "name": "sender",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InsufficientApproval",
                  "inputs": [
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidApprover",
                  "inputs": [
                      {
                          "name": "approver",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidOperator",
                  "inputs": [
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidOwner",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidReceiver",
                  "inputs": [
                      {
                          "name": "receiver",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidSender",
                  "inputs": [
                      {
                          "name": "sender",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721NonexistentToken",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "OwnableInvalidOwner",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "OwnableUnauthorizedAccount",
                  "inputs": [
                      {
                          "name": "account",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              }
          ],
      },
      TrustNFT: {
        address: "0x92f725c404d355645d5daf9d7ab7967f2f15a952",
        abi:           [
              {
                  "type": "function",
                  "name": "acceptOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "approve",
                  "inputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "pure"
              },
              {
                  "type": "function",
                  "name": "balanceOf",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getApproved",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getTrustData",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "data",
                          "type": "tuple",
                          "internalType": "struct TrustNFT.TrustData",
                          "components": [
                              {
                                  "name": "score",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "agreementsCompleted",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "agreementsDisputed",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "lastUpdated",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "mintedAt",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              }
                          ]
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getTrustDataByAgent",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "data",
                          "type": "tuple",
                          "internalType": "struct TrustNFT.TrustData",
                          "components": [
                              {
                                  "name": "score",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "agreementsCompleted",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "agreementsDisputed",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "lastUpdated",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "mintedAt",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              }
                          ]
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getTrustScore",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "score",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "isApprovedForAll",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "meetsThreshold",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "threshold",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "meets",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "mintTrustNFT",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "name",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "owner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "ownerOf",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "pendingOwner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "recordAgreementCompletion",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "success",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "renounceOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "safeTransferFrom",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "safeTransferFrom",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "data",
                          "type": "bytes",
                          "internalType": "bytes"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "setAgreementContract",
                  "inputs": [
                      {
                          "name": "newContract",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "setApprovalForAll",
                  "inputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "pure"
              },
              {
                  "type": "function",
                  "name": "supportsInterface",
                  "inputs": [
                      {
                          "name": "interfaceId",
                          "type": "bytes4",
                          "internalType": "bytes4"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "bool",
                          "internalType": "bool"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "symbol",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "tokenURI",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "",
                          "type": "string",
                          "internalType": "string"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "totalMinted",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "total",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "transferFrom",
                  "inputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "pure"
              },
              {
                  "type": "function",
                  "name": "transferOwnership",
                  "inputs": [
                      {
                          "name": "newOwner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "event",
                  "name": "AgreementCompleted",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "success",
                          "type": "bool",
                          "indexed": false,
                          "internalType": "bool"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementContractUpdated",
                  "inputs": [
                      {
                          "name": "oldContract",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newContract",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "Approval",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "approved",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "ApprovalForAll",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "operator",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "approved",
                          "type": "bool",
                          "indexed": false,
                          "internalType": "bool"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferStarted",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferred",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "Transfer",
                  "inputs": [
                      {
                          "name": "from",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "to",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "TrustNFTMinted",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "agent",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "initialScore",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "TrustScoreUpdated",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "oldScore",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      },
                      {
                          "name": "newScore",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "error",
                  "name": "ERC721IncorrectOwner",
                  "inputs": [
                      {
                          "name": "sender",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InsufficientApproval",
                  "inputs": [
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidApprover",
                  "inputs": [
                      {
                          "name": "approver",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidOperator",
                  "inputs": [
                      {
                          "name": "operator",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidOwner",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidReceiver",
                  "inputs": [
                      {
                          "name": "receiver",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721InvalidSender",
                  "inputs": [
                      {
                          "name": "sender",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ERC721NonexistentToken",
                  "inputs": [
                      {
                          "name": "tokenId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "OwnableInvalidOwner",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "OwnableUnauthorizedAccount",
                  "inputs": [
                      {
                          "name": "account",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "TrustNFT__AlreadyMinted",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "TrustNFT__InvalidScore",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "TrustNFT__NotAgreementContract",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "TrustNFT__NotMinted",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "TrustNFT__NotTransferable",
                  "inputs": []
              }
          ],
      },
      ServiceAgreement: {
        address: "0xc9caaa6d70b8b2f73d96d7154cb8c2c97ec16bb4",
        abi:           [
              {
                  "type": "function",
                  "name": "acceptAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "acceptOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "cancelAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "createAgreement",
                  "inputs": [
                      {
                          "name": "provider",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "token",
                          "type": "address",
                          "internalType": "address"
                      },
                      {
                          "name": "amount",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "trustThreshold",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "deadline",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "serviceHash",
                          "type": "bytes32",
                          "internalType": "bytes32"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "disputeAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "fulfillAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      },
                      {
                          "name": "outputHash",
                          "type": "bytes32",
                          "internalType": "bytes32"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "getAgentAgreements",
                  "inputs": [
                      {
                          "name": "agent",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "ids",
                          "type": "uint256[]",
                          "internalType": "uint256[]"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "getAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [
                      {
                          "name": "agreement",
                          "type": "tuple",
                          "internalType": "struct ServiceAgreement.Agreement",
                          "components": [
                              {
                                  "name": "requester",
                                  "type": "address",
                                  "internalType": "address"
                              },
                              {
                                  "name": "provider",
                                  "type": "address",
                                  "internalType": "address"
                              },
                              {
                                  "name": "token",
                                  "type": "address",
                                  "internalType": "address"
                              },
                              {
                                  "name": "amount",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "trustThreshold",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "deadline",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "serviceHash",
                                  "type": "bytes32",
                                  "internalType": "bytes32"
                              },
                              {
                                  "name": "outputHash",
                                  "type": "bytes32",
                                  "internalType": "bytes32"
                              },
                              {
                                  "name": "status",
                                  "type": "uint8",
                                  "internalType": "enum ServiceAgreement.AgreementStatus"
                              },
                              {
                                  "name": "createdAt",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              },
                              {
                                  "name": "settledAt",
                                  "type": "uint256",
                                  "internalType": "uint256"
                              }
                          ]
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "owner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "pendingOwner",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "renounceOwnership",
                  "inputs": [],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "settleAgreement",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "function",
                  "name": "totalAgreements",
                  "inputs": [],
                  "outputs": [
                      {
                          "name": "total",
                          "type": "uint256",
                          "internalType": "uint256"
                      }
                  ],
                  "stateMutability": "view"
              },
              {
                  "type": "function",
                  "name": "transferOwnership",
                  "inputs": [
                      {
                          "name": "newOwner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ],
                  "outputs": [],
                  "stateMutability": "nonpayable"
              },
              {
                  "type": "event",
                  "name": "AgreementAccepted",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementCancelled",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementCreated",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "requester",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "provider",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "amount",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      },
                      {
                          "name": "trustThreshold",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementDisputed",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "disputer",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementExpired",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementFulfilled",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "outputHash",
                          "type": "bytes32",
                          "indexed": false,
                          "internalType": "bytes32"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "AgreementSettled",
                  "inputs": [
                      {
                          "name": "agreementId",
                          "type": "uint256",
                          "indexed": true,
                          "internalType": "uint256"
                      },
                      {
                          "name": "amount",
                          "type": "uint256",
                          "indexed": false,
                          "internalType": "uint256"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferStarted",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "event",
                  "name": "OwnershipTransferred",
                  "inputs": [
                      {
                          "name": "previousOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      },
                      {
                          "name": "newOwner",
                          "type": "address",
                          "indexed": true,
                          "internalType": "address"
                      }
                  ],
                  "anonymous": false
              },
              {
                  "type": "error",
                  "name": "OwnableInvalidOwner",
                  "inputs": [
                      {
                          "name": "owner",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "OwnableUnauthorizedAccount",
                  "inputs": [
                      {
                          "name": "account",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ReentrancyGuardReentrantCall",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "SafeERC20FailedOperation",
                  "inputs": [
                      {
                          "name": "token",
                          "type": "address",
                          "internalType": "address"
                      }
                  ]
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__DeadlinePassed",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__InvalidStatus",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__NotFound",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__NotParticipant",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__NotProvider",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__NotRequester",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__SameAgent",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__TrustBelowThreshold",
                  "inputs": []
              },
              {
                  "type": "error",
                  "name": "ServiceAgreement__ZeroAmount",
                  "inputs": []
              }
          ],
      },
  },
} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
