// Autogenerated by scripts/foundry-bridge.js
// DO NOT EDIT MANUALLY — regenerate after each deployment.
//
// Placeholder: Run `node scripts/foundry-bridge.js --chain-id 8453` after deploying contracts.

import type { GenericContractsDeclaration } from "@/utils/scaffold/contract";

const deployedContracts = {
  // Will be populated by foundry-bridge.js after deployment
  // Example:
  // "8453": {
  //   AgentRegistry: {
  //     address: "0x...",
  //     abi: [...],
  //   },
  // },
} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
